from __future__ import annotations

import base64
import hashlib
import io
import re
import zipfile
from html import escape
from typing import Literal

from plotter_core.models import (
    CloseCommand,
    CubicCommand,
    DesignDocument,
    DesignLayer,
    DesignPath,
    LineCommand,
    MoveCommand,
    ProjectRecipe,
    QuadraticCommand,
    SvgExportBundle,
    SvgExportManifestEntry,
)


def _format(value: float) -> str:
    rendered = f"{value:.4f}".rstrip("0").rstrip(".")
    return "0" if rendered in {"", "-0"} else rendered


def _path_data(path: DesignPath, height_mm: float) -> str:
    parts: list[str] = []
    for command in path.commands:
        if isinstance(command, MoveCommand):
            parts.append(f"M {_format(command.point.x)} {_format(height_mm - command.point.y)}")
        elif isinstance(command, LineCommand):
            parts.append(f"L {_format(command.point.x)} {_format(height_mm - command.point.y)}")
        elif isinstance(command, QuadraticCommand):
            parts.append(
                "Q "
                f"{_format(command.control.x)} {_format(height_mm - command.control.y)} "
                f"{_format(command.point.x)} {_format(height_mm - command.point.y)}"
            )
        elif isinstance(command, CubicCommand):
            parts.append(
                "C "
                f"{_format(command.control1.x)} {_format(height_mm - command.control1.y)} "
                f"{_format(command.control2.x)} {_format(height_mm - command.control2.y)} "
                f"{_format(command.point.x)} {_format(height_mm - command.point.y)}"
            )
        elif isinstance(command, CloseCommand):
            parts.append("Z")
    return " ".join(parts)


def _svg(design: DesignDocument, layers: list[DesignLayer]) -> str:
    page = design.page
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        (
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'width="{_format(page.width_mm)}mm" height="{_format(page.height_mm)}mm" '
            f'viewBox="0 0 {_format(page.width_mm)} {_format(page.height_mm)}">'
        ),
        "  <metadata>Generated by Plotbox from machine-independent design geometry.</metadata>",
    ]
    for layer in layers:
        lines.append(
            f'  <g id="{escape(layer.layer_id)}" '
            f'data-semantic-role="{escape(layer.semantic_role)}" '
            f'fill="none" stroke="{escape(layer.preview_color)}" stroke-width="0.3">'
        )
        for path in layer.paths:
            lines.append(
                f'    <path id="{escape(path.path_id)}" d="{_path_data(path, page.height_mm)}"/>'
            )
        lines.append("  </g>")
    lines.append("</svg>")
    return "\n".join(lines) + "\n"


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "pass"


def _deterministic_zip(files: dict[str, bytes]) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for filename in sorted(files):
            info = zipfile.ZipInfo(filename=filename, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, files[filename])
    return buffer.getvalue()


def export_svg_bundle(recipe: ProjectRecipe, design: DesignDocument) -> SvgExportBundle:
    layer_by_id = {layer.layer_id: layer for layer in design.layers}
    layer_by_role = {layer.semantic_role: layer for layer in design.layers}
    files: dict[str, bytes] = {}
    entries: list[SvgExportManifestEntry] = []

    def add(
        filename: str,
        content: str,
        kind: Literal["pass", "combined"],
        pass_id: str | None = None,
    ) -> None:
        payload = content.encode("utf-8")
        files[filename] = payload
        entries.append(
            SvgExportManifestEntry(
                filename=filename,
                sha256=hashlib.sha256(payload).hexdigest(),
                byte_count=len(payload),
                kind=kind,
                pass_id=pass_id,
            )
        )

    enabled_layers: list[DesignLayer] = []
    for index, plot_pass in enumerate(
        (item for item in recipe.passes if item.enabled),
        start=1,
    ):
        layers = (
            [
                layer_by_id[layer_id]
                for layer_id in plot_pass.source_layer_ids
                if layer_id in layer_by_id
            ]
            if plot_pass.source_layer_ids
            else [layer_by_role[plot_pass.semantic_role]]
            if plot_pass.semantic_role in layer_by_role
            else []
        )
        if not layers:
            continue
        recolored = [
            layer.model_copy(update={"preview_color": plot_pass.preview_color}) for layer in layers
        ]
        enabled_layers.extend(recolored)
        add(
            f"{index:02d}-{_slug(plot_pass.name)}.svg",
            _svg(design, recolored),
            "pass",
            plot_pass.pass_id,
        )
    add("combined.svg", _svg(design, enabled_layers), "combined")
    return SvgExportBundle(
        project_id=recipe.project_id,
        design_sha256=design.metadata.normalized_sha256,
        entries=entries,
        archive_base64=base64.b64encode(_deterministic_zip(files)).decode("ascii"),
    )
