param(
    [Parameter(Mandatory = $true, Position = 0)]
    [ValidateNotNullOrEmpty()]
    [string]$ProjectPath
)

$ErrorActionPreference = 'Stop'

$Package = Split-Path -Parent $MyInvocation.MyCommand.Path
$Overlay = Join-Path $Package 'overlay'

function Test-PlotboxRoot {
    param([string]$Path)

    $RequiredRelativePaths = @(
        'packages/plotter_core/plotter_core/models.py'
        'packages/plotter_core/plotter_core/maps/osm.py'
        'apps/web/src/maps/MapControls.tsx'
        'services/api/plotterapp_api/main.py'
    )

    foreach ($RelativePath in $RequiredRelativePaths) {
        if (-not (Test-Path -LiteralPath (Join-Path $Path $RelativePath))) {
            return $false
        }
    }

    return $true
}

try {
    $Root = (Resolve-Path -LiteralPath $ProjectPath -ErrorAction Stop).Path
} catch {
    throw "ProjectPath does not exist: $ProjectPath"
}

if (-not (Test-PlotboxRoot -Path $Root)) {
    throw "ProjectPath is not the Plotbox repository root: $Root"
}

Write-Host "using Plotbox repository $Root"

function Decode-Text {
    param([string]$Base64)
    return [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Base64))
}

function Replace-Once {
    param([string]$Path, [string]$Old, [string]$New)

    $Text = [System.IO.File]::ReadAllText($Path, [System.Text.Encoding]::UTF8)
    $UsesCrLf = $Text.Contains("`r`n")

    # Match using LF so Windows Git checkouts with core.autocrlf/CRLF do not break patches.
    $NormalizedText = $Text.Replace("`r`n", "`n")
    $NormalizedOld = $Old.Replace("`r`n", "`n")
    $NormalizedNew = $New.Replace("`r`n", "`n")

    $Index = $NormalizedText.IndexOf($NormalizedOld, [System.StringComparison]::Ordinal)
    if ($Index -lt 0) {
        throw "Expected source block was not found in $Path. The repository file differs from the version this bundle was built against."
    }

    $Updated =
        $NormalizedText.Substring(0, $Index) +
        $NormalizedNew +
        $NormalizedText.Substring($Index + $NormalizedOld.Length)

    if ($UsesCrLf) {
        $Updated = $Updated.Replace("`n", "`r`n")
    }

    [System.IO.File]::WriteAllText($Path, $Updated, (New-Object System.Text.UTF8Encoding($false)))
}

function Append-Once {
    param([string]$Path, [string]$Marker, [string]$Content)
    $Text = [System.IO.File]::ReadAllText($Path, [System.Text.Encoding]::UTF8)
    if ($Text.Contains($Marker)) { return }
    $Updated = $Text.TrimEnd() + "`n`n" + $Content.TrimEnd() + "`n"
    [System.IO.File]::WriteAllText($Path, $Updated, (New-Object System.Text.UTF8Encoding($false)))
}

function Copy-Overlay {
    Get-ChildItem -Path $Overlay -File -Recurse | ForEach-Object {
        $Relative = [System.IO.Path]::GetRelativePath($Overlay, $_.FullName)
        $Target = Join-Path $Root $Relative
        $TargetDirectory = Split-Path -Parent $Target
        if (-not (Test-Path $TargetDirectory)) { New-Item -ItemType Directory -Path $TargetDirectory -Force | Out-Null }
        Copy-Item -LiteralPath $_.FullName -Destination $Target -Force
        Write-Host "replaced $Relative"
    }
}

function Apply-Patches {
    $Path = Join-Path $Root 'packages/plotter_core/plotter_core/models.py'
    $Old = Decode-Text 'Y2xhc3MgT3NtRmVhdHVyZVRvZ2dsZXMoU3RyaWN0TW9kZWwpOgogICAgcm9hZHM6IGJvb2wgPSBUcnVlCiAgICBidWlsZGluZ3M6IGJvb2wgPSBUcnVlCiAgICB3YXRlcjogYm9vbCA9IFRydWUKICAgIHJhaWw6IGJvb2wgPSBUcnVlCiAgICBwYXJrczogYm9vbCA9IFRydWUKCgpjbGFzcyBPc21SZW5kZXJSdWxlcyhTdHJpY3RNb2RlbCk6CiAgICByb2FkX2xpbmVfdHJlYXRtZW50OiBMaXRlcmFsWyJjZW50ZXJsaW5lIiwgImNhc2luZyIsICJwYXJhbGxlbCJdID0gImNlbnRlcmxpbmUiCiAgICByb2FkX3dpZHRoX21tOiBmbG9hdCA9IEZpZWxkKGRlZmF1bHQ9MC44LCBndD0wLCBsZT0xMCkKICAgIGJ1aWxkaW5nX3RyZWF0bWVudDogTGl0ZXJhbFsib3V0bGluZSIsICJoYXRjaCJdID0gIm91dGxpbmUiCiAgICB3YXRlcl90cmVhdG1lbnQ6IExpdGVyYWxbIm91dGxpbmUiLCAiaGF0Y2giXSA9ICJoYXRjaCIKICAgIHBhcmtfdHJlYXRtZW50OiBMaXRlcmFsWyJvdXRsaW5lIiwgImhhdGNoIl0gPSAib3V0bGluZSIKICAgIHBvbHlnb25faGF0Y2hfc3BhY2luZ19tbTogZmxvYXQgPSBGaWVsZChkZWZhdWx0PTIuMCwgZ3Q9MCwgbGU9MzApCiAgICBwb2x5Z29uX2hhdGNoX2FuZ2xlX2RlZ3JlZXM6IGZsb2F0ID0gRmllbGQoZGVmYXVsdD00NSwgZ2U9LTM2MCwgbGU9MzYwKQogICAgc2ltcGxpZmljYXRpb25fdG9sZXJhbmNlX21tOiBmbG9hdCA9IEZpZWxkKGRlZmF1bHQ9MC4wOCwgZ2U9MCwgbGU9MTApCiAgICBtaW5pbXVtX2ZlYXR1cmVfbW06IGZsb2F0ID0gRmllbGQoZGVmYXVsdD0wLjMsIGdlPTAsIGxlPTIwKQoKCmNsYXNzIE9zbVNuYXBzaG90TWV0YWRhdGEoU3RyaWN0TW9kZWwpOgo='
    $New = Decode-Text 'Y2xhc3MgT3NtRmVhdHVyZVRvZ2dsZXMoU3RyaWN0TW9kZWwpOgogICAgIyBMZWdhY3kgZ3JvdXAgc3dpdGNoZXMgcmVtYWluIGZvciBjb21wYXRpYmlsaXR5IHdpdGggZXhpc3Rpbmcgc2F2ZWQgcHJvamVjdHMuCiAgICByb2FkczogYm9vbCA9IFRydWUKICAgIGJ1aWxkaW5nczogYm9vbCA9IFRydWUKICAgIHdhdGVyOiBib29sID0gVHJ1ZQogICAgcmFpbDogYm9vbCA9IFRydWUKICAgIHBhcmtzOiBib29sID0gVHJ1ZQoKICAgIHJvYWRfbW90b3J3YXlzOiBib29sID0gVHJ1ZQogICAgcm9hZF9wcmltYXJ5OiBib29sID0gVHJ1ZQogICAgcm9hZF9zZWNvbmRhcnk6IGJvb2wgPSBUcnVlCiAgICByb2FkX3Jlc2lkZW50aWFsOiBib29sID0gVHJ1ZQogICAgcm9hZF9zZXJ2aWNlOiBib29sID0gVHJ1ZQogICAgZm9vdHBhdGhzOiBib29sID0gVHJ1ZQogICAgcGVkZXN0cmlhbl9wYXRoczogYm9vbCA9IFRydWUKICAgIGN5Y2xld2F5czogYm9vbCA9IFRydWUKICAgIHRyYWNrczogYm9vbCA9IFRydWUKCiAgICB3YXRlcl9hcmVhczogYm9vbCA9IFRydWUKICAgIHdhdGVyd2F5czogYm9vbCA9IFRydWUKICAgIGNvYXN0bGluZTogYm9vbCA9IEZhbHNlCgogICAgd29vZGxhbmQ6IGJvb2wgPSBGYWxzZQogICAgZmFybWxhbmQ6IGJvb2wgPSBGYWxzZQogICAgbWVhZG93OiBib29sID0gRmFsc2UKICAgIHJlc2lkZW50aWFsX2xhbmR1c2U6IGJvb2wgPSBGYWxzZQogICAgaW5kdXN0cmlhbF9sYW5kdXNlOiBib29sID0gRmFsc2UKICAgIGNlbWV0ZXJ5OiBib29sID0gRmFsc2UKICAgIHBhcmtpbmc6IGJvb2wgPSBGYWxzZQogICAgd2V0bGFuZHM6IGJvb2wgPSBGYWxzZQoKICAgIGJvdW5kYXJpZXM6IGJvb2wgPSBGYWxzZQogICAgcG93ZXJfbGluZXM6IGJvb2wgPSBGYWxzZQogICAgcG93ZXJfbm9kZXM6IGJvb2wgPSBGYWxzZQogICAgYWVyb3dheTogYm9vbCA9IEZhbHNlCiAgICBtYXJpdGltZTogYm9vbCA9IEZhbHNlCgogICAgcG9pbnRzX29mX2ludGVyZXN0OiBib29sID0gRmFsc2UKICAgIHBvaV93b3JzaGlwOiBib29sID0gRmFsc2UKICAgIHBvaV9zdGF0aW9uczogYm9vbCA9IEZhbHNlCiAgICBwb2lfcGVha3M6IGJvb2wgPSBGYWxzZQogICAgcG9pX2hpc3RvcmljOiBib29sID0gRmFsc2UKICAgIHBvaV9jYXN0bGVzOiBib29sID0gRmFsc2UKICAgIHBvaV9saWdodGhvdXNlczogYm9vbCA9IEZhbHNlCiAgICBwb2lfd2luZF90dXJiaW5lczogYm9vbCA9IEZhbHNlCiAgICBwb2lfc2Nob29sczogYm9vbCA9IEZhbHNlCiAgICBwb2lfaG9zcGl0YWxzOiBib29sID0gRmFsc2UKICAgIHBvaV90cmVlczogYm9vbCA9IEZhbHNlCiAgICBwb2lfbW9udW1lbnRzOiBib29sID0gRmFsc2UKCgpQb2x5Z29uVHJlYXRtZW50ID0gTGl0ZXJhbFsKICAgICJvdXRsaW5lIiwgImhhdGNoIiwgIm91dGxpbmUtaGF0Y2giLCAiY3Jvc3NoYXRjaCIsICJzdGlwcGxlIiwgInJpcHBsZSIKXQoKCmNsYXNzIE9zbVJlbmRlclJ1bGVzKFN0cmljdE1vZGVsKToKICAgIHJvYWRfbGluZV90cmVhdG1lbnQ6IExpdGVyYWxbCiAgICAgICAgImNlbnRlcmxpbmUiLCAiY2FzaW5nIiwgInBhcmFsbGVsIiwgImNsYXNzaWZpZWQiLCAiZGFzaGVkIiwgImRvdHRlZCIKICAgIF0gPSAiY2VudGVybGluZSIKICAgIHJvYWRfd2lkdGhfbW06IGZsb2F0ID0gRmllbGQoZGVmYXVsdD0wLjgsIGd0PTAsIGxlPTEwKQogICAgcmFpbF90cmVhdG1lbnQ6IExpdGVyYWxbInNpbmdsZSIsICJkb3VibGUiLCAic2xlZXBlcnMiLCAiY2xhc3NpZmllZCJdID0gInNpbmdsZSIKICAgIHJhaWxfd2lkdGhfbW06IGZsb2F0ID0gRmllbGQoZGVmYXVsdD0xLjAsIGd0PTAsIGxlPTEwKQogICAgcmFpbF9zbGVlcGVyX3NwYWNpbmdfbW06IGZsb2F0ID0gRmllbGQoZGVmYXVsdD0yLjUsIGd0PTAsIGxlPTIwKQogICAgYnVpbGRpbmdfdHJlYXRtZW50OiBQb2x5Z29uVHJlYXRtZW50ID0gIm91dGxpbmUiCiAgICB3YXRlcl90cmVhdG1lbnQ6IFBvbHlnb25UcmVhdG1lbnQgPSAiaGF0Y2giCiAgICBwYXJrX3RyZWF0bWVudDogUG9seWdvblRyZWF0bWVudCA9ICJvdXRsaW5lIgogICAgbGFuZHVzZV90cmVhdG1lbnQ6IFBvbHlnb25UcmVhdG1lbnQgPSAib3V0bGluZSIKICAgIGJvdW5kYXJ5X3RyZWF0bWVudDogTGl0ZXJhbFsic29saWQiLCAiZGFzaGVkIiwgImRvdHRlZCIsICJkYXNoLWRvdCJdID0gImRhc2hlZCIKICAgIHBvbHlnb25faGF0Y2hfc3BhY2luZ19tbTogZmxvYXQgPSBGaWVsZChkZWZhdWx0PTIuMCwgZ3Q9MCwgbGU9MzApCiAgICBwb2x5Z29uX2hhdGNoX2FuZ2xlX2RlZ3JlZXM6IGZsb2F0ID0gRmllbGQoZGVmYXVsdD00NSwgZ2U9LTM2MCwgbGU9MzYwKQogICAgZGFzaF9sZW5ndGhfbW06IGZsb2F0ID0gRmllbGQoZGVmYXVsdD0yLjAsIGd0PTAsIGxlPTMwKQogICAgZGFzaF9nYXBfbW06IGZsb2F0ID0gRmllbGQoZGVmYXVsdD0xLjAsIGd0PTAsIGxlPTMwKQogICAgZG90X2xlbmd0aF9tbTogZmxvYXQgPSBGaWVsZChkZWZhdWx0PTAuMiwgZ3Q9MCwgbGU9NSkKICAgIGRvdF9nYXBfbW06IGZsb2F0ID0gRmllbGQoZGVmYXVsdD0xLjAsIGd0PTAsIGxlPTMwKQogICAgYnJpZGdlX3RpY2tfc3BhY2luZ19tbTogZmxvYXQgPSBGaWVsZChkZWZhdWx0PTMuMCwgZ3Q9MCwgbGU9MzApCiAgICBicmlkZ2VfdGlja193aWR0aF9tbTogZmxvYXQgPSBGaWVsZChkZWZhdWx0PTEuMiwgZ3Q9MCwgbGU9MTApCiAgICBidWlsZGluZ19zaGFkb3dfZW5hYmxlZDogYm9vbCA9IEZhbHNlCiAgICBidWlsZGluZ19zaGFkb3dfb2Zmc2V0X21tOiBmbG9hdCA9IEZpZWxkKGRlZmF1bHQ9MS4wLCBnZT0wLCBsZT0yMCkKICAgIGJ1aWxkaW5nX3NoYWRvd19hbmdsZV9kZWdyZWVzOiBmbG9hdCA9IEZpZWxkKGRlZmF1bHQ9NDUsIGdlPS0zNjAsIGxlPTM2MCkKICAgIHdhdGVyX3JpcHBsZV9zcGFjaW5nX21tOiBmbG9hdCA9IEZpZWxkKGRlZmF1bHQ9Mi4wLCBndD0wLCBsZT0zMCkKICAgIHdhdGVyX3JpcHBsZV9hbmdsZV9kZWdyZWVzOiBmbG9hdCA9IEZpZWxkKGRlZmF1bHQ9MCwgZ2U9LTM2MCwgbGU9MzYwKQogICAgIyBLZXB0IGFzIGFsaWFzZXMgZm9yIG9sZGVyIHByb2plY3QgZmlsZXMvVUkgY29kZS4gTmV3IGdlbmVyYXRpb24gdXNlcyBPc21EZXRhaWxGaWx0ZXJpbmcuCiAgICBzaW1wbGlmaWNhdGlvbl90b2xlcmFuY2VfbW06IGZsb2F0ID0gRmllbGQoZGVmYXVsdD0wLjA4LCBnZT0wLCBsZT0xMCkKICAgIG1pbmltdW1fZmVhdHVyZV9tbTogZmxvYXQgPSBGaWVsZChkZWZhdWx0PTAuMywgZ2U9MCwgbGU9MjApCgoKY2xhc3MgT3NtUG9pU2V0dGluZ3MoU3RyaWN0TW9kZWwpOgogICAgc3ltYm9sX3NpemVfbW06IGZsb2F0ID0gRmllbGQoZGVmYXVsdD0yLjAsIGdlPTAuNSwgbGU9MTApCgoKY2xhc3MgT3NtRGV0YWlsRmlsdGVyaW5nKFN0cmljdE1vZGVsKToKICAgIG1pbmltdW1fbGluZV9sZW5ndGhfbW06IGZsb2F0ID0gRmllbGQoZGVmYXVsdD0wLjMsIGdlPTAsIGxlPTUwKQogICAgbWluaW11bV9wb2x5Z29uX2FyZWFfbW0yOiBmbG9hdCA9IEZpZWxkKGRlZmF1bHQ9MC41LCBnZT0wLCBsZT01MDAwKQogICAgbWluaW11bV9wb2lfc3BhY2luZ19tbTogZmxvYXQgPSBGaWVsZChkZWZhdWx0PTIuMCwgZ2U9MCwgbGU9NTApCiAgICB2ZXJ0ZXhfc2ltcGxpZmljYXRpb25fdG9sZXJhbmNlX21tOiBmbG9hdCA9IEZpZWxkKGRlZmF1bHQ9MC4wOCwgZ2U9MCwgbGU9MTApCiAgICBtaW5pbXVtX2dhcF9tbTogZmxvYXQgPSBGaWVsZChkZWZhdWx0PTAuMCwgZ2U9MCwgbGU9MjApCgoKY2xhc3MgT3NtVGVycmFpblNldHRpbmdzKFN0cmljdE1vZGVsKToKICAgIGVuYWJsZWQ6IGJvb2wgPSBGYWxzZQogICAgcHJvdmlkZXI6IExpdGVyYWxbImF3cy10ZXJyYXJpdW0iXSA9ICJhd3MtdGVycmFyaXVtIgogICAgY29udG91cl9pbnRlcnZhbF9tOiBmbG9hdCA9IEZpZWxkKGRlZmF1bHQ9MTAuMCwgZ3Q9MCwgbGU9NTAwKQogICAgaW5kZXhfY29udG91cl9ldmVyeTogaW50ID0gRmllbGQoZGVmYXVsdD01LCBnZT0xLCBsZT0yMCkKICAgIHNhbXBsZV9yZXNvbHV0aW9uOiBpbnQgPSBGaWVsZChkZWZhdWx0PTEyOCwgZ2U9MTYsIGxlPTUxMikKICAgIGNvbnRvdXJfc2ltcGxpZmljYXRpb25fbW06IGZsb2F0ID0gRmllbGQoZGVmYXVsdD0wLjE1LCBnZT0wLCBsZT0xMCkKICAgIG1pbmltdW1fY29udG91cl9sZW5ndGhfbW06IGZsb2F0ID0gRmllbGQoZGVmYXVsdD0yLjAsIGdlPTAsIGxlPTEwMCkKICAgIGVsZXZhdGlvbl9taW5fbTogZmxvYXQgfCBOb25lID0gTm9uZQogICAgZWxldmF0aW9uX21heF9tOiBmbG9hdCB8IE5vbmUgPSBOb25lCgogICAgQG1vZGVsX3ZhbGlkYXRvcihtb2RlPSJhZnRlciIpCiAgICBkZWYgZWxldmF0aW9uX3JhbmdlX2lzX3ZhbGlkKHNlbGYpIC0+IE9zbVRlcnJhaW5TZXR0aW5nczoKICAgICAgICBpZiAoCiAgICAgICAgICAgIHNlbGYuZWxldmF0aW9uX21pbl9tIGlzIG5vdCBOb25lCiAgICAgICAgICAgIGFuZCBzZWxmLmVsZXZhdGlvbl9tYXhfbSBpcyBub3QgTm9uZQogICAgICAgICAgICBhbmQgc2VsZi5lbGV2YXRpb25fbWluX20gPiBzZWxmLmVsZXZhdGlvbl9tYXhfbQogICAgICAgICk6CiAgICAgICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoIm1pbmltdW0gdGVycmFpbiBlbGV2YXRpb24gbXVzdCBub3QgZXhjZWVkIG1heGltdW0gZWxldmF0aW9uIikKICAgICAgICByZXR1cm4gc2VsZgoKCmNsYXNzIE9zbVNuYXBzaG90TWV0YWRhdGEoU3RyaWN0TW9kZWwpOgo='
    Replace-Once -Path $Path -Old $Old -New $New

    $Path = Join-Path $Root 'packages/plotter_core/plotter_core/models.py'
    $Old = Decode-Text 'Y2xhc3MgT3NtU2V0dGluZ3MoU3RyaWN0TW9kZWwpOgogICAgc2VsZWN0aW9uOiBPc21TZWxlY3Rpb24gPSBGaWVsZChkZWZhdWx0X2ZhY3Rvcnk9T3NtU2VsZWN0aW9uKQogICAgZmVhdHVyZXM6IE9zbUZlYXR1cmVUb2dnbGVzID0gRmllbGQoZGVmYXVsdF9mYWN0b3J5PU9zbUZlYXR1cmVUb2dnbGVzKQogICAgcmVuZGVyOiBPc21SZW5kZXJSdWxlcyA9IEZpZWxkKGRlZmF1bHRfZmFjdG9yeT1Pc21SZW5kZXJSdWxlcykKICAgIHNuYXBzaG90OiBPc21TbmFwc2hvdE1ldGFkYXRhIHwgTm9uZSA9IE5vbmUK'
    $New = Decode-Text 'Y2xhc3MgT3NtU2V0dGluZ3MoU3RyaWN0TW9kZWwpOgogICAgc2VsZWN0aW9uOiBPc21TZWxlY3Rpb24gPSBGaWVsZChkZWZhdWx0X2ZhY3Rvcnk9T3NtU2VsZWN0aW9uKQogICAgZmVhdHVyZXM6IE9zbUZlYXR1cmVUb2dnbGVzID0gRmllbGQoZGVmYXVsdF9mYWN0b3J5PU9zbUZlYXR1cmVUb2dnbGVzKQogICAgcmVuZGVyOiBPc21SZW5kZXJSdWxlcyA9IEZpZWxkKGRlZmF1bHRfZmFjdG9yeT1Pc21SZW5kZXJSdWxlcykKICAgIHBvaTogT3NtUG9pU2V0dGluZ3MgPSBGaWVsZChkZWZhdWx0X2ZhY3Rvcnk9T3NtUG9pU2V0dGluZ3MpCiAgICBkZXRhaWw6IE9zbURldGFpbEZpbHRlcmluZyA9IEZpZWxkKGRlZmF1bHRfZmFjdG9yeT1Pc21EZXRhaWxGaWx0ZXJpbmcpCiAgICB0ZXJyYWluOiBPc21UZXJyYWluU2V0dGluZ3MgPSBGaWVsZChkZWZhdWx0X2ZhY3Rvcnk9T3NtVGVycmFpblNldHRpbmdzKQogICAgcHJlc2V0X2lkOiBMaXRlcmFsWwogICAgICAgICJzdHJlZXQiLAogICAgICAgICJmaWd1cmUtZ3JvdW5kIiwKICAgICAgICAiaHlkcm9sb2d5IiwKICAgICAgICAidG9wb2dyYXBoaWMiLAogICAgICAgICJyYWlsIiwKICAgICAgICAibGFuZHNjYXBlIiwKICAgICAgICAidXJiYW4tZGV0YWlsIiwKICAgIF0gfCBOb25lID0gTm9uZQogICAgc25hcHNob3Q6IE9zbVNuYXBzaG90TWV0YWRhdGEgfCBOb25lID0gTm9uZQo='
    Replace-Once -Path $Path -Old $Old -New $New

    $Path = Join-Path $Root 'apps/web/src/types.ts'
    $Old = Decode-Text 'ZXhwb3J0IGludGVyZmFjZSBPc21TZXR0aW5ncyB7CiAgc2VsZWN0aW9uOiB7CiAgICBib3VuZHM6IE9zbUJvdW5kczsKICAgIHJvdGF0aW9uX2RlZ3JlZXM6IG51bWJlcjsKICAgIGxvY2tfbW9kZTogImV4dGVudCIgfCAic2NhbGUiOwogIH07CiAgZmVhdHVyZXM6IHsKICAgIHJvYWRzOiBib29sZWFuOwogICAgYnVpbGRpbmdzOiBib29sZWFuOwogICAgd2F0ZXI6IGJvb2xlYW47CiAgICByYWlsOiBib29sZWFuOwogICAgcGFya3M6IGJvb2xlYW47CiAgfTsKICByZW5kZXI6IHsKICAgIHJvYWRfbGluZV90cmVhdG1lbnQ6ICJjZW50ZXJsaW5lIiB8ICJjYXNpbmciIHwgInBhcmFsbGVsIjsKICAgIHJvYWRfd2lkdGhfbW06IG51bWJlcjsKICAgIGJ1aWxkaW5nX3RyZWF0bWVudDogIm91dGxpbmUiIHwgImhhdGNoIjsKICAgIHdhdGVyX3RyZWF0bWVudDogIm91dGxpbmUiIHwgImhhdGNoIjsKICAgIHBhcmtfdHJlYXRtZW50OiAib3V0bGluZSIgfCAiaGF0Y2giOwogICAgcG9seWdvbl9oYXRjaF9zcGFjaW5nX21tOiBudW1iZXI7CiAgICBwb2x5Z29uX2hhdGNoX2FuZ2xlX2RlZ3JlZXM6IG51bWJlcjsKICAgIHNpbXBsaWZpY2F0aW9uX3RvbGVyYW5jZV9tbTogbnVtYmVyOwogICAgbWluaW11bV9mZWF0dXJlX21tOiBudW1iZXI7CiAgfTsKICBzbmFwc2hvdDogT3NtU25hcHNob3RNZXRhZGF0YSB8IG51bGw7Cn0K'
    $New = Decode-Text 'ZXhwb3J0IHR5cGUgT3NtUG9seWdvblRyZWF0bWVudCA9CiAgfCAib3V0bGluZSIKICB8ICJoYXRjaCIKICB8ICJvdXRsaW5lLWhhdGNoIgogIHwgImNyb3NzaGF0Y2giCiAgfCAic3RpcHBsZSIKICB8ICJyaXBwbGUiOwoKZXhwb3J0IGludGVyZmFjZSBPc21TZXR0aW5ncyB7CiAgc2VsZWN0aW9uOiB7CiAgICBib3VuZHM6IE9zbUJvdW5kczsKICAgIHJvdGF0aW9uX2RlZ3JlZXM6IG51bWJlcjsKICAgIGxvY2tfbW9kZTogImV4dGVudCIgfCAic2NhbGUiOwogIH07CiAgZmVhdHVyZXM6IHsKICAgIHJvYWRzOiBib29sZWFuOwogICAgYnVpbGRpbmdzOiBib29sZWFuOwogICAgd2F0ZXI6IGJvb2xlYW47CiAgICByYWlsOiBib29sZWFuOwogICAgcGFya3M6IGJvb2xlYW47CiAgICByb2FkX21vdG9yd2F5czogYm9vbGVhbjsKICAgIHJvYWRfcHJpbWFyeTogYm9vbGVhbjsKICAgIHJvYWRfc2Vjb25kYXJ5OiBib29sZWFuOwogICAgcm9hZF9yZXNpZGVudGlhbDogYm9vbGVhbjsKICAgIHJvYWRfc2VydmljZTogYm9vbGVhbjsKICAgIGZvb3RwYXRoczogYm9vbGVhbjsKICAgIHBlZGVzdHJpYW5fcGF0aHM6IGJvb2xlYW47CiAgICBjeWNsZXdheXM6IGJvb2xlYW47CiAgICB0cmFja3M6IGJvb2xlYW47CiAgICB3YXRlcl9hcmVhczogYm9vbGVhbjsKICAgIHdhdGVyd2F5czogYm9vbGVhbjsKICAgIGNvYXN0bGluZTogYm9vbGVhbjsKICAgIHdvb2RsYW5kOiBib29sZWFuOwogICAgZmFybWxhbmQ6IGJvb2xlYW47CiAgICBtZWFkb3c6IGJvb2xlYW47CiAgICByZXNpZGVudGlhbF9sYW5kdXNlOiBib29sZWFuOwogICAgaW5kdXN0cmlhbF9sYW5kdXNlOiBib29sZWFuOwogICAgY2VtZXRlcnk6IGJvb2xlYW47CiAgICBwYXJraW5nOiBib29sZWFuOwogICAgd2V0bGFuZHM6IGJvb2xlYW47CiAgICBib3VuZGFyaWVzOiBib29sZWFuOwogICAgcG93ZXJfbGluZXM6IGJvb2xlYW47CiAgICBwb3dlcl9ub2RlczogYm9vbGVhbjsKICAgIGFlcm93YXk6IGJvb2xlYW47CiAgICBtYXJpdGltZTogYm9vbGVhbjsKICAgIHBvaW50c19vZl9pbnRlcmVzdDogYm9vbGVhbjsKICAgIHBvaV93b3JzaGlwOiBib29sZWFuOwogICAgcG9pX3N0YXRpb25zOiBib29sZWFuOwogICAgcG9pX3BlYWtzOiBib29sZWFuOwogICAgcG9pX2hpc3RvcmljOiBib29sZWFuOwogICAgcG9pX2Nhc3RsZXM6IGJvb2xlYW47CiAgICBwb2lfbGlnaHRob3VzZXM6IGJvb2xlYW47CiAgICBwb2lfd2luZF90dXJiaW5lczogYm9vbGVhbjsKICAgIHBvaV9zY2hvb2xzOiBib29sZWFuOwogICAgcG9pX2hvc3BpdGFsczogYm9vbGVhbjsKICAgIHBvaV90cmVlczogYm9vbGVhbjsKICAgIHBvaV9tb251bWVudHM6IGJvb2xlYW47CiAgfTsKICByZW5kZXI6IHsKICAgIHJvYWRfbGluZV90cmVhdG1lbnQ6CiAgICAgIHwgImNlbnRlcmxpbmUiCiAgICAgIHwgImNhc2luZyIKICAgICAgfCAicGFyYWxsZWwiCiAgICAgIHwgImNsYXNzaWZpZWQiCiAgICAgIHwgImRhc2hlZCIKICAgICAgfCAiZG90dGVkIjsKICAgIHJvYWRfd2lkdGhfbW06IG51bWJlcjsKICAgIHJhaWxfdHJlYXRtZW50OiAic2luZ2xlIiB8ICJkb3VibGUiIHwgInNsZWVwZXJzIiB8ICJjbGFzc2lmaWVkIjsKICAgIHJhaWxfd2lkdGhfbW06IG51bWJlcjsKICAgIHJhaWxfc2xlZXBlcl9zcGFjaW5nX21tOiBudW1iZXI7CiAgICBidWlsZGluZ190cmVhdG1lbnQ6IE9zbVBvbHlnb25UcmVhdG1lbnQ7CiAgICB3YXRlcl90cmVhdG1lbnQ6IE9zbVBvbHlnb25UcmVhdG1lbnQ7CiAgICBwYXJrX3RyZWF0bWVudDogT3NtUG9seWdvblRyZWF0bWVudDsKICAgIGxhbmR1c2VfdHJlYXRtZW50OiBPc21Qb2x5Z29uVHJlYXRtZW50OwogICAgYm91bmRhcnlfdHJlYXRtZW50OiAic29saWQiIHwgImRhc2hlZCIgfCAiZG90dGVkIiB8ICJkYXNoLWRvdCI7CiAgICBwb2x5Z29uX2hhdGNoX3NwYWNpbmdfbW06IG51bWJlcjsKICAgIHBvbHlnb25faGF0Y2hfYW5nbGVfZGVncmVlczogbnVtYmVyOwogICAgZGFzaF9sZW5ndGhfbW06IG51bWJlcjsKICAgIGRhc2hfZ2FwX21tOiBudW1iZXI7CiAgICBkb3RfbGVuZ3RoX21tOiBudW1iZXI7CiAgICBkb3RfZ2FwX21tOiBudW1iZXI7CiAgICBicmlkZ2VfdGlja19zcGFjaW5nX21tOiBudW1iZXI7CiAgICBicmlkZ2VfdGlja193aWR0aF9tbTogbnVtYmVyOwogICAgYnVpbGRpbmdfc2hhZG93X2VuYWJsZWQ6IGJvb2xlYW47CiAgICBidWlsZGluZ19zaGFkb3dfb2Zmc2V0X21tOiBudW1iZXI7CiAgICBidWlsZGluZ19zaGFkb3dfYW5nbGVfZGVncmVlczogbnVtYmVyOwogICAgd2F0ZXJfcmlwcGxlX3NwYWNpbmdfbW06IG51bWJlcjsKICAgIHdhdGVyX3JpcHBsZV9hbmdsZV9kZWdyZWVzOiBudW1iZXI7CiAgICBzaW1wbGlmaWNhdGlvbl90b2xlcmFuY2VfbW06IG51bWJlcjsKICAgIG1pbmltdW1fZmVhdHVyZV9tbTogbnVtYmVyOwogIH07CiAgcG9pOiB7CiAgICBzeW1ib2xfc2l6ZV9tbTogbnVtYmVyOwogIH07CiAgZGV0YWlsOiB7CiAgICBtaW5pbXVtX2xpbmVfbGVuZ3RoX21tOiBudW1iZXI7CiAgICBtaW5pbXVtX3BvbHlnb25fYXJlYV9tbTI6IG51bWJlcjsKICAgIG1pbmltdW1fcG9pX3NwYWNpbmdfbW06IG51bWJlcjsKICAgIHZlcnRleF9zaW1wbGlmaWNhdGlvbl90b2xlcmFuY2VfbW06IG51bWJlcjsKICAgIG1pbmltdW1fZ2FwX21tOiBudW1iZXI7CiAgfTsKICB0ZXJyYWluOiB7CiAgICBlbmFibGVkOiBib29sZWFuOwogICAgcHJvdmlkZXI6ICJhd3MtdGVycmFyaXVtIjsKICAgIGNvbnRvdXJfaW50ZXJ2YWxfbTogbnVtYmVyOwogICAgaW5kZXhfY29udG91cl9ldmVyeTogbnVtYmVyOwogICAgc2FtcGxlX3Jlc29sdXRpb246IG51bWJlcjsKICAgIGNvbnRvdXJfc2ltcGxpZmljYXRpb25fbW06IG51bWJlcjsKICAgIG1pbmltdW1fY29udG91cl9sZW5ndGhfbW06IG51bWJlcjsKICAgIGVsZXZhdGlvbl9taW5fbTogbnVtYmVyIHwgbnVsbDsKICAgIGVsZXZhdGlvbl9tYXhfbTogbnVtYmVyIHwgbnVsbDsKICB9OwogIHByZXNldF9pZDoKICAgIHwgInN0cmVldCIKICAgIHwgImZpZ3VyZS1ncm91bmQiCiAgICB8ICJoeWRyb2xvZ3kiCiAgICB8ICJ0b3BvZ3JhcGhpYyIKICAgIHwgInJhaWwiCiAgICB8ICJsYW5kc2NhcGUiCiAgICB8ICJ1cmJhbi1kZXRhaWwiCiAgICB8IG51bGw7CiAgc25hcHNob3Q6IE9zbVNuYXBzaG90TWV0YWRhdGEgfCBudWxsOwp9Cg=='
    Replace-Once -Path $Path -Old $Old -New $New

    $Path = Join-Path $Root 'services/api/plotterapp_api/main.py'
    $Old = Decode-Text 'ICAgICAgICBkZWYgcnVuX21hcCgKICAgICAgICAgICAgY3VycmVudDogUHJvamVjdFJlY2lwZSwKICAgICAgICAgICAgY2hlY2twb2ludDogUHJvZ3Jlc3NDYWxsYmFjayB8IE5vbmUgPSBOb25lLAogICAgICAgICAgICBfOiBDYW5jZWxsYXRpb25Ub2tlbiB8IE5vbmUgPSBOb25lLAogICAgICAgICkgLT4gRGVzaWduRG9jdW1lbnQ6CiAgICAgICAgICAgIHJldHVybiBnZW5lcmF0ZV9vc21fZGVzaWduKHNuYXBzaG90LCBjdXJyZW50LCBwcm9ncmVzcz1jaGVja3BvaW50KQoKICAgICAgICByZXR1cm4gIm1hcC5vcGVuc3RyZWV0bWFwIiwgIjEuMC4wIiwgcnVuX21hcAo='
    $New = Decode-Text 'ICAgICAgICBkZWYgcnVuX21hcCgKICAgICAgICAgICAgY3VycmVudDogUHJvamVjdFJlY2lwZSwKICAgICAgICAgICAgY2hlY2twb2ludDogUHJvZ3Jlc3NDYWxsYmFjayB8IE5vbmUgPSBOb25lLAogICAgICAgICAgICB0b2tlbjogQ2FuY2VsbGF0aW9uVG9rZW4gfCBOb25lID0gTm9uZSwKICAgICAgICApIC0+IERlc2lnbkRvY3VtZW50OgogICAgICAgICAgICByZXR1cm4gZ2VuZXJhdGVfb3NtX2Rlc2lnbigKICAgICAgICAgICAgICAgIHNuYXBzaG90LAogICAgICAgICAgICAgICAgY3VycmVudCwKICAgICAgICAgICAgICAgIHByb2dyZXNzPWNoZWNrcG9pbnQsCiAgICAgICAgICAgICAgICBjYW5jZWw9dG9rZW4uY2hlY2twb2ludCBpZiB0b2tlbiBpcyBub3QgTm9uZSBlbHNlIE5vbmUsCiAgICAgICAgICAgICkKCiAgICAgICAgcmV0dXJuICJtYXAub3BlbnN0cmVldG1hcCIsICIyLjAuMCIsIHJ1bl9tYXAK'
    Replace-Once -Path $Path -Old $Old -New $New

    $Path = Join-Path $Root 'services/api/plotterapp_api/main.py'
    $Old = Decode-Text 'ICAgICAgICB2ZXJzaW9uPSIwLjMuMCIsCg=='
    $New = Decode-Text 'ICAgICAgICB2ZXJzaW9uPSIwLjQuMSIsCg=='
    Replace-Once -Path $Path -Old $Old -New $New

    $Path = Join-Path $Root 'services/api/plotterapp_api/main.py'
    $Old = Decode-Text 'ICAgICAgICAgICAgTW9kZU1hbmlmZXN0KAogICAgICAgICAgICAgICAga2luZD0iaW1wb3J0ZXIiLAogICAgICAgICAgICAgICAgaWQ9Im1hcC5vcGVuc3RyZWV0bWFwIiwKICAgICAgICAgICAgICAgIHZlcnNpb249IjEuMC4wIiwKICAgICAgICAgICAgICAgIG5hbWU9Ik9wZW5TdHJlZXRNYXAiLAogICAgICAgICAgICAgICAgZGVzY3JpcHRpb249IlNlbWFudGljIHZlY3RvciBtYXAgYXJ0d29yayBmcm9tIGEgZnJvemVuIE9TTSBzbmFwc2hvdC4iLAogICAgICAgICAgICAgICAgY2F0ZWdvcnk9Im1hcCIsCiAgICAgICAgICAgICAgICBxdWFsaXR5X2xldmVscz1xdWFsaXR5X2xldmVscywKICAgICAgICAgICAgICAgIHNlbWFudGljX3JvbGVzPVsKICAgICAgICAgICAgICAgICAgICAicm9hZC1tYWpvciIsCiAgICAgICAgICAgICAgICAgICAgInJvYWQtc2Vjb25kYXJ5IiwKICAgICAgICAgICAgICAgICAgICAicm9hZC1sb2NhbCIsCiAgICAgICAgICAgICAgICAgICAgInJvYWQtcGF0aCIsCiAgICAgICAgICAgICAgICAgICAgImJ1aWxkaW5ncyIsCiAgICAgICAgICAgICAgICAgICAgIndhdGVyIiwKICAgICAgICAgICAgICAgICAgICAicmFpbCIsCiAgICAgICAgICAgICAgICAgICAgInBhcmtzIiwKICAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICksCg=='
    $New = Decode-Text 'ICAgICAgICAgICAgTW9kZU1hbmlmZXN0KAogICAgICAgICAgICAgICAga2luZD0iaW1wb3J0ZXIiLAogICAgICAgICAgICAgICAgaWQ9Im1hcC5vcGVuc3RyZWV0bWFwIiwKICAgICAgICAgICAgICAgIHZlcnNpb249IjIuMC4wIiwKICAgICAgICAgICAgICAgIG5hbWU9Ik9wZW5TdHJlZXRNYXAiLAogICAgICAgICAgICAgICAgZGVzY3JpcHRpb249IlNlbWFudGljIHZlY3RvciBtYXAgYXJ0d29yayB3aXRoIHBsb3QgdHJlYXRtZW50cywgUE9JcywgYW5kIGNvbnRvdXJzLiIsCiAgICAgICAgICAgICAgICBjYXRlZ29yeT0ibWFwIiwKICAgICAgICAgICAgICAgIHF1YWxpdHlfbGV2ZWxzPXF1YWxpdHlfbGV2ZWxzLAogICAgICAgICAgICAgICAgc2VtYW50aWNfcm9sZXM9WwogICAgICAgICAgICAgICAgICAgICJyb2FkLW1ham9yIiwKICAgICAgICAgICAgICAgICAgICAicm9hZC1zZWNvbmRhcnkiLAogICAgICAgICAgICAgICAgICAgICJyb2FkLWxvY2FsIiwKICAgICAgICAgICAgICAgICAgICAicm9hZC1wYXRoIiwKICAgICAgICAgICAgICAgICAgICAiYnVpbGRpbmdzIiwKICAgICAgICAgICAgICAgICAgICAid2F0ZXIiLAogICAgICAgICAgICAgICAgICAgICJ3YXRlcndheSIsCiAgICAgICAgICAgICAgICAgICAgImNvYXN0bGluZSIsCiAgICAgICAgICAgICAgICAgICAgInJhaWwiLAogICAgICAgICAgICAgICAgICAgICJwYXJrcyIsCiAgICAgICAgICAgICAgICAgICAgImZvcmVzdCIsCiAgICAgICAgICAgICAgICAgICAgImZhcm1sYW5kIiwKICAgICAgICAgICAgICAgICAgICAibWVhZG93IiwKICAgICAgICAgICAgICAgICAgICAibGFuZHVzZS1yZXNpZGVudGlhbCIsCiAgICAgICAgICAgICAgICAgICAgImxhbmR1c2UtaW5kdXN0cmlhbCIsCiAgICAgICAgICAgICAgICAgICAgImNlbWV0ZXJ5IiwKICAgICAgICAgICAgICAgICAgICAicGFya2luZyIsCiAgICAgICAgICAgICAgICAgICAgIndldGxhbmQiLAogICAgICAgICAgICAgICAgICAgICJib3VuZGFyeSIsCiAgICAgICAgICAgICAgICAgICAgInBvd2VyLWxpbmUiLAogICAgICAgICAgICAgICAgICAgICJwb3dlci1ub2RlIiwKICAgICAgICAgICAgICAgICAgICAiYWVyb3dheS1ydW53YXkiLAogICAgICAgICAgICAgICAgICAgICJhZXJvd2F5LXRheGl3YXkiLAogICAgICAgICAgICAgICAgICAgICJtYXJpdGltZSIsCiAgICAgICAgICAgICAgICAgICAgInBvaS13b3JzaGlwIiwKICAgICAgICAgICAgICAgICAgICAicG9pLXN0YXRpb24iLAogICAgICAgICAgICAgICAgICAgICJwb2ktcGVhayIsCiAgICAgICAgICAgICAgICAgICAgInBvaS1oaXN0b3JpYyIsCiAgICAgICAgICAgICAgICAgICAgInBvaS1jYXN0bGUiLAogICAgICAgICAgICAgICAgICAgICJwb2ktbGlnaHRob3VzZSIsCiAgICAgICAgICAgICAgICAgICAgInBvaS13aW5kLXR1cmJpbmUiLAogICAgICAgICAgICAgICAgICAgICJwb2ktc2Nob29sIiwKICAgICAgICAgICAgICAgICAgICAicG9pLWhvc3BpdGFsIiwKICAgICAgICAgICAgICAgICAgICAicG9pLXRyZWUiLAogICAgICAgICAgICAgICAgICAgICJwb2ktbW9udW1lbnQiLAogICAgICAgICAgICAgICAgICAgICJ0ZXJyYWluLWNvbnRvdXIiLAogICAgICAgICAgICAgICAgICAgICJ0ZXJyYWluLWluZGV4LWNvbnRvdXIiLAogICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgKSwK'
    Replace-Once -Path $Path -Old $Old -New $New

    $Path = Join-Path $Root 'packages/plotter_core/plotter_core/maps/__init__.py'
    $Marker = Decode-Text 'IyB0ZXJyYWluIGV4cG9ydHMgdjAuNC4x'
    $Content = Decode-Text 'IyB0ZXJyYWluIGV4cG9ydHMgdjAuNC4xCmZyb20gcGxvdHRlcl9jb3JlLm1hcHMudGVycmFpbiBpbXBvcnQgKCAgIyBub3FhOiBFNDAyCiAgICBBd3NUZXJyYXJpdW1UZXJyYWluUHJvdmlkZXIsCiAgICBFbGV2YXRpb25HcmlkLAogICAgVGVycmFpblByb3ZpZGVyLAogICAgZ2VuZXJhdGVfY29udG91cnMsCikKCl9fYWxsX18gKz0gWwogICAgIkF3c1RlcnJhcml1bVRlcnJhaW5Qcm92aWRlciIsCiAgICAiRWxldmF0aW9uR3JpZCIsCiAgICAiVGVycmFpblByb3ZpZGVyIiwKICAgICJnZW5lcmF0ZV9jb250b3VycyIsCl0K'
    Append-Once -Path $Path -Marker $Marker -Content $Content

    $Path = Join-Path $Root 'apps/web/package.json'
    $Old = Decode-Text 'ICAidmVyc2lvbiI6ICIwLjMuNSIsCg=='
    $New = Decode-Text 'ICAidmVyc2lvbiI6ICIwLjQuMSIsCg=='
    Replace-Once -Path $Path -Old $Old -New $New

    $Path = Join-Path $Root 'config.yaml'
    $Old = Decode-Text 'dmVyc2lvbjogIjAuMy41Igo='
    $New = Decode-Text 'dmVyc2lvbjogIjAuNC4xIgo='
    Replace-Once -Path $Path -Old $Old -New $New

    $Path = Join-Path $Root 'apps/web/src/index.css'
    $Marker = Decode-Text 'TWFwIGNvbnRyb2xzIC0gdmVyc2lvbiAwLjQuMQ=='
    $Content = Decode-Text 'LyogTWFwIGNvbnRyb2xzIC0gdmVyc2lvbiAwLjQuMSAqLwoubWFwLWNvbnRyb2wtc2VjdGlvbnMgewogIGRpc3BsYXk6IGdyaWQ7CiAgZ2FwOiA3cHg7Cn0KCi5tYXAtY29udHJvbC1zZWN0aW9ucyA+IGRldGFpbHMgewogIGJvcmRlcjogMXB4IHNvbGlkICNjN2MwYjM7CiAgYmFja2dyb3VuZDogI2ZmZmRmNzsKfQoKLm1hcC1jb250cm9sLXNlY3Rpb25zID4gZGV0YWlscyA+IHN1bW1hcnkgewogIHBhZGRpbmc6IDlweCAxMHB4OwogIGN1cnNvcjogcG9pbnRlcjsKICBjb2xvcjogdmFyKC0tbW9zcyk7CiAgZm9udC1zaXplOiAxMHB4OwogIGZvbnQtd2VpZ2h0OiA4MDA7CiAgbGV0dGVyLXNwYWNpbmc6IDAuMDRlbTsKICB0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlOwp9CgoubWFwLWNvbnRyb2wtc2VjdGlvbnMgPiBkZXRhaWxzW29wZW5dID4gc3VtbWFyeSB7CiAgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkICNkZGQ2Yzk7CiAgYmFja2dyb3VuZDogI2VlZWFkZjsKfQoKLm1hcC1jb250cm9sLXNlY3Rpb25zID4gZGV0YWlscyA+IDpub3Qoc3VtbWFyeSkgewogIG1hcmdpbi1sZWZ0OiAxMHB4OwogIG1hcmdpbi1yaWdodDogMTBweDsKfQoKLm1hcC1jb250cm9sLXNlY3Rpb25zID4gZGV0YWlscyA+IDpsYXN0LWNoaWxkIHsKICBtYXJnaW4tYm90dG9tOiAxMHB4Owp9CgoubWFwLXByZXNldC1ncmlkIHsKICBtYXJnaW4tdG9wOiAxMHB4OwogIGRpc3BsYXk6IGdyaWQ7CiAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoMiwgbWlubWF4KDAsIDFmcikpOwogIGdhcDogNXB4Owp9CgoubWFwLXByZXNldC1ncmlkIGJ1dHRvbiB7CiAgbWluLXdpZHRoOiAwOwogIHBhZGRpbmc6IDdweCA2cHg7CiAgYm9yZGVyOiAxcHggc29saWQgI2FhYTQ5NzsKICBiYWNrZ3JvdW5kOiAjZmZmZGY3OwogIGNvbG9yOiB2YXIoLS1pbmspOwogIGZvbnQtc2l6ZTogOXB4OwogIHRleHQtdHJhbnNmb3JtOiBjYXBpdGFsaXplOwp9CgoubWFwLXByZXNldC1ncmlkIGJ1dHRvbi5zZWxlY3RlZCB7CiAgYm9yZGVyLWNvbG9yOiB2YXIoLS1tb3NzKTsKICBiYWNrZ3JvdW5kOiB2YXIoLS1saW1lKTsKICBib3gtc2hhZG93OiBpbnNldCAwIC0ycHggMCB2YXIoLS1tb3NzKTsKfQo='
    Append-Once -Path $Path -Marker $Marker -Content $Content

    $Path = Join-Path $Root 'README.md'
    $Marker = Decode-Text 'IyMgRXh0ZW5kZWQgcGVuLXBsb3QgbWFwIGxheWVycyAoMC40LjEp'
    $Content = Decode-Text 'IyMgRXh0ZW5kZWQgcGVuLXBsb3QgbWFwIGxheWVycyAoMC40LjEpCgpUaGUgT3BlblN0cmVldE1hcCB3b3Jrc3BhY2Ugbm93IGV4cG9zZXMgZ3JvdXBlZCB0cmFuc3BvcnQsIHdhdGVyLCBsYW5kdXNlLCBib3VuZGFyeSwKaW5mcmFzdHJ1Y3R1cmUgYW5kIFBPSSBjb250cm9scyByYXRoZXIgdGhhbiB0cmVhdGluZyB0aGUgc291cmNlIGFzIGEgY29udmVudGlvbmFsIHJhc3RlciBtYXAuClJvYWRzIGNhbiB1c2UgY2VudGVybGluZSwgY2FzaW5nLCBjbGFzc2lmaWVkLCBkYXNoZWQgb3IgZG90dGVkIHRyZWF0bWVudHM7IHJhaWwgY2FuIHVzZSBzaW5nbGUsCmRvdWJsZSBvciBzbGVlcGVyIGdlb21ldHJ5LiBQb2x5Z29uIHNvdXJjZXMgc3VwcG9ydCBvdXRsaW5lLCBoYXRjaCwgb3V0bGluZStoYXRjaCwgY3Jvc3NoYXRjaCBhbmQKcGxvdHRlci1zYWZlIHN0aXBwbGUgdHJlYXRtZW50cywgd2l0aCBhIHBhcmFsbGVsIHJpcHBsZSBvcHRpb24gZm9yIHdhdGVyLgoKUGh5c2ljYWwgZGV0YWlsIGZpbHRlcmluZyBpcyBhcHBsaWVkIGFmdGVyIGdlb2dyYXBoaWMgY29vcmRpbmF0ZXMgYXJlIHRyYW5zZm9ybWVkIHRvIHBhZ2UKbWlsbGltZXRyZXMuIE1pbmltdW0gbGluZSBsZW5ndGgsIHBvbHlnb24gYXJlYSwgUE9JIHNwYWNpbmcgYW5kIHZlcnRleCBzaW1wbGlmaWNhdGlvbiB0aGVyZWZvcmUKdHJhY2sgdGhlIGFjdHVhbCBwbG90dGVkIHNpemUgcmF0aGVyIHRoYW4gc291cmNlLW1hcCB1bml0cy4KCk9wdGlvbmFsIHRlcnJhaW4gY29udG91cnMgdXNlIHRoZSBwdWJsaWMgQVdTIE9wZW4gRGF0YSBUZXJyYWluIFRpbGVzIFRlcnJhcml1bSBQTkcgc291cmNlLiBUZXJyYWluCnBpeGVscyBhcmUgZGVjb2RlZCB0byBlbGV2YXRpb24sIGNvbnRvdXJlZCB3aXRoIG1hcmNoaW5nIHNxdWFyZXMgYW5kIGNvbnZlcnRlZCB0byBub3JtYWwgUGxvdGJveAp2ZWN0b3IgcGF0aHM7IHRlcnJhaW4gaW1hZ2VyeSBpcyBuZXZlciBhZGRlZCB0byB0aGUgcGxvdC4gU3RhbmRhcmQgYW5kIGluZGV4IGNvbnRvdXJzIGFyZSBlbWl0dGVkCmFzIHNlcGFyYXRlIHNlbWFudGljIHJvbGVzLiBOZXR3b3JrIGFjY2VzcyBpcyByZXF1aXJlZCBvbmx5IHdoaWxlIHRlcnJhaW4gY29udG91cnMgYXJlIGdlbmVyYXRlZC4K'
    Append-Once -Path $Path -Marker $Marker -Content $Content

}

function Run-OptionalTools {
    if (Get-Command uv -ErrorAction SilentlyContinue) {
        & uv run python scripts/export_schemas.py
        if ($LASTEXITCODE -ne 0) { throw 'Schema regeneration failed' }
        Write-Host 'regenerated packages/schemas'
    } else {
        Write-Host "uv not found - run 'uv run python scripts/export_schemas.py' before committing"
    }

    if (Get-Command pnpm -ErrorAction SilentlyContinue) {
        Push-Location (Join-Path $Root 'apps/web')
        try {
            & pnpm exec prettier --write src/maps/MapControls.tsx src/types.ts src/index.css
            if ($LASTEXITCODE -ne 0) { throw 'Frontend formatting failed' }
            Write-Host 'formatted changed frontend files'
        } finally {
            Pop-Location
        }
    } else {
        Write-Host 'pnpm not found - run frontend formatting before committing'
    }
}

Apply-Patches
Copy-Overlay
Run-OptionalTools
Write-Host 'Plotbox map expansion v0.4.4 applied.'
