import { mkdirSync, writeFileSync } from 'node:fs';
import { CYBERPUNK_ASSETS, CYBERPUNK_PALETTE } from '../apps/web/src/components/isometricCyberpunkGlyphs.ts';

const out = 'artifacts/cyberpunk';
mkdirSync(`${out}/tiles`, { recursive: true });
for (const asset of CYBERPUNK_ASSETS) writeFileSync(`${out}/tiles/${asset.id}.svg`, asset.svg);
const escape = (s: string) => s.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
const overview = CYBERPUNK_ASSETS.filter(a => !/-view-[123]$/.test(a.id));
const cols = 6, cellW = 220, cellH = 230;
writeFileSync(`${out}/collection.svg`, `<svg xmlns="http://www.w3.org/2000/svg" width="${cols*cellW}" height="${Math.ceil(overview.length/cols)*cellH+110}"><rect width="100%" height="100%" fill="#fff5df"/><text x="28" y="42" font-family="sans-serif" font-size="29" font-weight="bold" fill="#26213f">RETROWAVE / CYBERPUNK CITY</text><text x="28" y="72" font-family="sans-serif" font-size="14" fill="#855bc0">${CYBERPUNK_ASSETS.length} vector tiles / four building and boat views / six pen colours</text>${overview.map((a,i)=>`<g transform="translate(${i%cols*cellW},${Math.floor(i/cols)*cellH+100})">${a.svg.replace('<svg ','<svg x="15" y="5" width="190" height="185" ')}<text x="110" y="212" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#26213f">${escape(a.name.split(' · ').slice(1).filter(s=>s!=='front-right').join(' · '))}</text></g>`).join('')}</svg>`);
const groups = [...new Set(CYBERPUNK_ASSETS.map(a => a.name.split(' · ')[0]!))];
writeFileSync(`${out}/index.html`, `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Retrowave / Cyberpunk city</title><style>
*{box-sizing:border-box}body{margin:0;padding:40px;background:#171529;color:#fff5df;font:15px/1.6 system-ui}header{max-width:880px}h1{font-size:48px;line-height:1.1}h2{margin-top:48px;color:#23becb;font-size:22px;border-bottom:1px solid #626487;padding-bottom:10px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}article{background:#fff5df;color:#26213f;border-top:3px solid #ef4baf;padding:16px}img{width:100%;height:230px;object-fit:contain}a{color:inherit;text-decoration:none}article p{font-size:12px}.inks{display:flex;gap:18px;flex-wrap:wrap}.inks span{font-size:12px}.inks i{display:inline-block;width:14px;height:14px;margin-right:6px;border:1px solid #fff5df;vertical-align:middle}small{color:#ef4baf}@media(max-width:800px){body{padding:20px}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}h1{font-size:34px}}
</style><header><small>GLYPHBOX / ISOMETRIC COLLECTION</small><h1>Retrowave /<br>Cyberpunk city</h1><p>${CYBERPUNK_ASSETS.length} plot-ready tiles: houses, apartment blocks, industry, shops, neon landmarks, vehicles and waterfronts. Buildings and boats have four true isometric views. Generated cities mix the building views automatically.</p><div class="inks">${CYBERPUNK_PALETTE.map(p=>`<span><i style="background:${p.colour}"></i>${escape(p.name.split(' · ')[1]!)}</span>`).join('')}</div><p>In the city generator, reload glyphs and choose <b>Use Retrowave / Cyberpunk collection</b>. Choose a coastal or lakeside landscape for the boats and waterfront.</p></header>${groups.map(group=>`<section><h2>${escape(group)}</h2><div class="grid">${CYBERPUNK_ASSETS.filter(a=>a.name.startsWith(`${group} · `)).map(a=>`<article><a href="tiles/${a.id}.svg"><img src="tiles/${a.id}.svg" alt="${escape(a.name)}"><p>${escape(a.name.split(' · ').slice(1).join(' · '))}</p></a></article>`).join('')}</div></section>`).join('')}</html>`);
console.log(`Exported ${CYBERPUNK_ASSETS.length} tiles to ${out}/index.html`);
const directions = ['courtyard-house', 'tenement-block', 'neon-arcade', 'boat-0'].flatMap(id => CYBERPUNK_ASSETS.filter(a => a.id.startsWith(`cyberpunk-${id}-view-`)));
writeFileSync(`${out}/orientations.svg`, `<svg xmlns="http://www.w3.org/2000/svg" width="1120" height="1130"><rect width="100%" height="100%" fill="#fff5df"/><text x="24" y="38" font-family="sans-serif" font-size="26" fill="#26213f">RETROWAVE / FOUR DIRECTIONS</text>${directions.map((a,i)=>`<g transform="translate(${i%4*280},${Math.floor(i/4)*260+65})">${a.svg.replace('<svg ','<svg x="15" y="5" width="250" height="210" ')}<text x="140" y="240" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#26213f">${escape(a.name.split(' · ').slice(1).join(' · '))}</text></g>`).join('')}</svg>`);
