import { mkdirSync, writeFileSync } from 'node:fs';
import { ANTIQUITY_ASSETS, ANTIQUITY_PALETTE } from '../apps/web/src/components/isometricAntiquityGlyphs.ts';

const out = 'artifacts/antiquity';
mkdirSync(`${out}/tiles`, { recursive: true });
for (const asset of ANTIQUITY_ASSETS) writeFileSync(`${out}/tiles/${asset.id}.svg`, asset.svg);
const escape = (s: string) => s.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
const groups = [...new Set(ANTIQUITY_ASSETS.map(a => a.name.split(' · ')[0]!))];
writeFileSync(`${out}/index.html`, `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Antiquity — Rome & Greece</title>
<style>*{box-sizing:border-box}body{background:#f0e9db;color:#493c32;font:15px/1.5 Georgia,serif;margin:0;padding:48px}header{max-width:900px;margin-bottom:36px}.eyebrow{font:11px system-ui;letter-spacing:.22em;text-transform:uppercase}h1{font-size:52px;line-height:1.1;margin:16px 0}h2{font-size:27px;border-bottom:1px solid #cbbca5;padding-bottom:12px;margin-top:48px}.palette{display:flex;flex-wrap:wrap;gap:16px;font:12px system-ui}.palette i{display:inline-block;width:12px;height:12px;border-radius:50%;margin-right:7px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:18px}article{background:#fff5df;border:1px solid #d8cbb7;padding:18px;border-radius:4px}article img{display:block;width:100%;height:225px;object-fit:contain}article p{font:12px/1.5 system-ui;margin:16px 0 0;min-height:36px}a{color:inherit;text-decoration:none}article:hover{border-color:#b8583c}footer{margin:48px 0 0;font:12px system-ui}@media(max-width:600px){body{padding:20px}h1{font-size:38px}}</style>
<header><div class="eyebrow">Glyphbox / Isometric collection</div><h1>Antiquity<br>Rome & Greece</h1><p>${ANTIQUITY_ASSETS.length} plot-ready tiles. Terracotta rooftops, limestone colonnades, shaded courtyards, paved streets and an ancient Mediterranean waterfront.</p><div class="palette">${ANTIQUITY_PALETTE.map(c => `<span><i style="background:${c.colour}"></i>${escape(c.name.replace('Antiquity · ', ''))}</span>`).join('')}</div></header>
${groups.map(group => `<section><h2>${escape(group)} <small> / ${ANTIQUITY_ASSETS.filter(a => a.name.startsWith(`${group} · `)).length}</small></h2><div class="grid">${ANTIQUITY_ASSETS.filter(a => a.name.startsWith(`${group} · `)).map(a => `<article><a href="tiles/${a.id}.svg"><img src="tiles/${a.id}.svg" alt="${escape(a.name)}"><p>${escape(a.name.split(' · ').slice(1).join(' · '))}</p></a></article>`).join('')}</div></section>`).join('')}
<footer>Every illustration shares its SVG vertices with its plot geometry. Pale stone uses the paper. The 20 roads include all five connected shapes in four treatments.</footer></html>`);
const cols = 8, cellW = 220, cellH = 245, rows = Math.ceil(ANTIQUITY_ASSETS.length / cols);
writeFileSync(`${out}/collection.svg`, `<svg xmlns="http://www.w3.org/2000/svg" width="${cols * cellW}" height="${rows * cellH + 100}" viewBox="0 0 ${cols * cellW} ${rows * cellH + 100}"><rect width="100%" height="100%" fill="#fff5df"/><text x="30" y="44" font-family="Georgia,serif" font-size="32" fill="#493c32">ANTIQUITY / ROME &amp; GREECE</text><text x="30" y="73" font-family="sans-serif" font-size="15" fill="#758464">${ANTIQUITY_ASSETS.length} isometric tiles · Glyphbox collection</text>${ANTIQUITY_ASSETS.map((a, i) => `<g transform="translate(${(i % cols) * cellW},${Math.floor(i / cols) * cellH + 100})">${a.svg.replace('<svg ', '<svg x="15" y="10" width="190" height="195" ')}<text x="110" y="225" text-anchor="middle" font-size="10" font-family="sans-serif" fill="#493c32">${escape(a.name.split(' · ').slice(1).join(' · '))}</text></g>`).join('')}</svg>`);
console.log(`Exported ${ANTIQUITY_ASSETS.length} SVG tiles and illustrated catalogue to ${out}/index.html`);
console.log(`Bundled artwork: ${(JSON.stringify(ANTIQUITY_ASSETS).length / 1024 / 1024).toFixed(2)} MB`);
