import { mkdirSync, writeFileSync } from 'node:fs';
import { MEDIEVAL_ASSETS } from '../apps/web/src/components/isometricMedievalGlyphs.ts';

const out = 'artifacts/medieval';
mkdirSync(`${out}/tiles`, { recursive: true });
for (const asset of MEDIEVAL_ASSETS) writeFileSync(`${out}/tiles/${asset.id}.svg`, asset.svg);
const escape = (s: string) => s.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
const groups = [...new Set(MEDIEVAL_ASSETS.map(a => a.name.split(' · ')[0]!))];
writeFileSync(`${out}/index.html`, `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Medieval — towns & castles</title>
<style>*{box-sizing:border-box}body{background:#f0e9db;color:#493c32;font:15px/1.5 Georgia,serif;margin:0;padding:48px}header{max-width:900px;margin-bottom:36px}.eyebrow{font:11px system-ui;letter-spacing:.22em;text-transform:uppercase}h1{font-size:52px;line-height:1.1;margin:16px 0}h2{font-size:27px;border-bottom:1px solid #cbbca5;padding-bottom:12px;margin-top:48px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}article{background:#fff5df;border:1px solid #d8cbb7;padding:18px;border-radius:4px}article img{display:block;width:100%;height:225px;object-fit:contain}article p{font:12px/1.5 system-ui;margin:16px 0 0;min-height:36px}a{color:inherit;text-decoration:none}article:hover{border-color:#b8583c}footer{margin:48px 0 0;font:12px system-ui}@media(max-width:800px){body{padding:20px}h1{font-size:38px}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
<header><div class="eyebrow">Glyphbox / Isometric collection</div><h1>Medieval<br>Towns & castles</h1><p>${MEDIEVAL_ASSETS.length} plot-ready tiles, using the Antiquity collection’s six inks. Timber framing, steep tiled roofs, cobbled lanes, walled gardens and a working medieval waterfront.</p><p>Each building and vessel is drawn from four directions. Compare the views across each row: the geometry turns on the ground, while walls and roofs remain upright.</p></header>
${groups.map(group => `<section><h2>${escape(group)} <small> / ${MEDIEVAL_ASSETS.filter(a => a.name.startsWith(`${group} · `)).length}</small></h2><div class="grid">${MEDIEVAL_ASSETS.filter(a => a.name.startsWith(`${group} · `)).map(a => `<article><a href="tiles/${a.id}.svg"><img src="tiles/${a.id}.svg" alt="${escape(a.name)}"><p>${escape(a.name.split(' · ').slice(1).join(' · '))}</p></a></article>`).join('')}</div></section>`).join('')}
<footer>SVG previews and plot paths use the same vertices. Pale walls use the paper. Roads include all five connected shapes in three treatments.</footer></html>`);
// A compact overview shows the designs once; the HTML catalogue contains every view.
const overview = MEDIEVAL_ASSETS.filter(a => !/-view-[123]$/.test(a.id));
const cols = 7, cellW = 220, cellH = 250, rows = Math.ceil(overview.length / cols);
writeFileSync(`${out}/collection.svg`, `<svg xmlns="http://www.w3.org/2000/svg" width="${cols * cellW}" height="${rows * cellH + 100}" viewBox="0 0 ${cols * cellW} ${rows * cellH + 100}"><rect width="100%" height="100%" fill="#fff5df"/><text x="30" y="44" font-family="Georgia,serif" font-size="32" fill="#493c32">MEDIEVAL / TOWNS &amp; CASTLES</text><text x="30" y="73" font-family="sans-serif" font-size="15" fill="#758464">${MEDIEVAL_ASSETS.length} tiles including four building &amp; vessel orientations · Glyphbox collection</text>${overview.map((a, i) => `<g transform="translate(${(i % cols) * cellW},${Math.floor(i / cols) * cellH + 100})">${a.svg.replace('<svg ', '<svg x="15" y="10" width="190" height="195" ')}<text x="110" y="225" text-anchor="middle" font-size="10" font-family="sans-serif" fill="#493c32">${escape(a.name.split(' · ').slice(1).filter(s=>!s.startsWith('front-')).join(' · '))}</text></g>`).join('')}</svg>`);
console.log(`Exported ${MEDIEVAL_ASSETS.length} SVG tiles; ${overview.length} distinct designs. Catalogue: ${out}/index.html`);
const directions = ['timber-house', 'gatehouse', 'watermill', 'vessel-0'].flatMap(id => MEDIEVAL_ASSETS.filter(a => a.id.startsWith(`medieval-${id}-view-`)));
writeFileSync(`${out}/orientations.svg`, `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1300" viewBox="0 0 1200 1300"><rect width="100%" height="100%" fill="#fff5df"/><text x="25" y="40" font-family="Georgia,serif" font-size="28" fill="#493c32">MEDIEVAL / FOUR DIRECTIONS</text>${directions.map((a,i)=>`<g transform="translate(${i%4*300},${Math.floor(i/4)*305+65})">${a.svg.replace('<svg ', '<svg x="15" y="10" width="270" height="255" ')}<text x="150" y="290" text-anchor="middle" font-size="11" font-family="sans-serif" fill="#493c32">${escape(a.name.split(' · ').slice(1).join(' · '))}</text></g>`).join('')}</svg>`);
