import { mkdirSync, writeFileSync } from 'node:fs';
import { CYBERPUNK_GEL_ASSETS as assets, CYBERPUNK_GEL_PALETTE as palette, CYBERPUNK_GEL_PAPER as paper } from '../apps/web/src/components/isometricCyberpunkGelGlyphs.ts';
import { generateIsometric } from '../packages/algorithms/src/isometric.ts';

const out = 'artifacts/cyberpunk-gel';
mkdirSync(`${out}/tiles`, { recursive: true });
for (const a of assets) writeFileSync(`${out}/tiles/${a.id}.svg`, a.svg);
const escape = (s: string) => s.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
const overview = assets.filter(a => !/-view-[123]$/.test(a.id));
const cols = 6, cellW = 220, cellH = 230;
const collection = `<svg xmlns="http://www.w3.org/2000/svg" width="${cols*cellW}" height="${Math.ceil(overview.length/cols)*cellH+125}"><rect width="100%" height="100%" fill="${paper}"/><text x="28" y="40" font-family="sans-serif" font-size="29" font-weight="bold" fill="#e8f4ff">DARK RETROWAVE/CYBERPUNK CITYSCAPE</text><text x="28" y="71" font-family="sans-serif" font-size="14" fill="#65f2ff">122 tiles / luminous outlines / window light bars / untouched dark paper</text>${palette.map((p,i)=>`<circle cx="${35+i*26}" cy="97" r="6" fill="${p.colour}"/>`).join('')}${overview.map((a,i)=>`<g transform="translate(${i%cols*cellW},${Math.floor(i/cols)*cellH+125})">${a.svg.replace('<svg ','<svg x="15" y="5" width="190" height="185" ')}<text x="110" y="212" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#e8f4ff">${escape(a.name.split(' · ').slice(1).filter(s=>s!=='front-right').join(' · '))}</text></g>`).join('')}</svg>`;
writeFileSync(`${out}/collection.svg`, collection);
writeFileSync(`${out}/collection-black.svg`, collection.replaceAll(paper, '#1c1d1f'));
const groups = [...new Set(assets.map(a => a.name.split(' · ')[0]!))];
writeFileSync(`${out}/index.html`, `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dark retrowave/cyberpunk cityscape</title><style>
:root{--paper:${paper}}*{box-sizing:border-box}body{margin:0;padding:40px;background:var(--paper);color:#e8f4ff;font:15px/1.6 system-ui}header{max-width:850px}h1{font-size:48px;line-height:1.1}h2{margin-top:48px;color:#65f2ff;font-size:22px;border-bottom:1px solid #c5a3ff;padding-bottom:10px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}article{border:1px solid #384366;padding:16px}article svg{width:100%;height:230px}svg [fill="${paper}"]{fill:var(--paper)}a{color:inherit;text-decoration:none}article p{font-size:12px}.inks{display:flex;gap:18px;flex-wrap:wrap}.inks span{font-size:12px}.inks i{display:inline-block;width:14px;height:14px;margin-right:6px;vertical-align:middle}small{color:#ff74da}button{margin:12px 8px 0 0;border:1px solid #65f2ff;background:transparent;color:#e8f4ff;padding:10px 20px;cursor:pointer;border-radius:4px}button[aria-pressed=true]{background:#65f2ff;color:#10172d}@media(max-width:800px){body{padding:20px}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}h1{font-size:34px}}
</style><header><small>GLYPHBOX / DARK PAPER EDITION</small><h1>Dark retrowave/<br>cyberpunk cityscape</h1><p>${assets.length} tiles retain the buildings, cars, boats and four-view rotations of the original city. Bright contours replace filled roofs and walls; windows become single light bars, and the grids leave more paper exposed.</p><div class="inks">${palette.map(p=>`<span><i style="background:${p.colour}"></i>${escape(p.name.split(' · ')[1]!)}</span>`).join('')}</div><p>Reload glyphs, then select <b>Use Dark retrowave/cyberpunk cityscape</b>. This selects navy paper, outlines and six gel passes. You can switch to Black under Paper colour. Pen width starts at 0.45 mm; match it to your gel pens.</p><button data-paper="${paper}" aria-pressed="true">Navy paper</button><button data-paper="#1c1d1f" aria-pressed="false">Black paper</button><p><small>Screen colours illustrate the palette; actual ink appearance depends on your pens and paper.</small></p></header>${groups.map(group=>`<section><h2>${escape(group)}</h2><div class="grid">${assets.filter(a=>a.name.startsWith(`${group} · `)).map(a=>`<article><a href="tiles/${a.id}.svg" aria-label="${escape(a.name)}">${a.svg}<p>${escape(a.name.split(' · ').slice(1).join(' · '))}</p></a></article>`).join('')}</div></section>`).join('')}<script>document.querySelectorAll('button[data-paper]').forEach(button=>button.addEventListener('click',()=>{document.documentElement.style.setProperty('--paper',button.dataset.paper);document.querySelectorAll('button[data-paper]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));</script></html>`);

const featured = ['courtyard-house', 'tenement-block', 'robot-factory', 'neon-arcade', 'synth-cinema', 'prism-tower'].map(id => assets.find(a => a.id === `cyberpunk-gel-${id}-view-0`)!);
writeFileSync(`${out}/preview.svg`, `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="900"><rect width="1200" height="900" fill="${paper}"/><text x="45" y="62" fill="#e8f4ff" font-family="sans-serif" font-size="30" font-weight="bold">DARK RETROWAVE/CYBERPUNK CITYSCAPE</text><text x="45" y="100" fill="#65f2ff" font-family="sans-serif" font-size="18">Cyberpunk / bright gel pens on navy paper</text>${featured.map((a,i)=>`<g transform="translate(${i%3*400},${Math.floor(i/3)*350+145})">${a.svg.replace('<svg ','<svg x="35" y="0" width="330" height="280" ')}<text x="200" y="317" fill="#e8f4ff" text-anchor="middle" font-family="sans-serif" font-size="14">${escape(a.name.split(' · ')[1]!)}</text></g>`).join('')}</svg>`);
console.log(`Exported ${assets.length} dark-paper tiles and black/navy previews to ${out}`);

// Review the actual plotted city as well as individual SVG thumbnails: exposed
// paving is generated separately from the artwork and must stay equally sparse.
const scene = generateIsometric({ preset: 'A3', orientation: 'landscape', widthMm: 420, heightMm: 297, marginMm: 10 }, {
  cells: 12, landscape: 'lake', fillMode: 'outline',
  buildingCategories: ['iso-cyberpunk-gel'], roadCategories: ['iso-cyberpunk-gel'],
  colourPasses: Object.fromEntries(palette.map(p => [p.colour, p.colour])),
}, assets.map(a => ({ id: a.id, name: a.name, role: a.isometricRole!, categoryId: a.categoryId, collectionId: a.collectionId, terrain: a.terrain, shoreMask: a.shoreMask, treeLined: a.treeLined, paths: a.plotPaths! })), palette.map(p => p.colour));
writeFileSync(`${out}/scene.svg`, `<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="990" viewBox="0 0 420 297"><rect width="420" height="297" fill="${paper}"/><g fill="none" stroke-width=".45" stroke-linecap="round" stroke-linejoin="round">${scene.paths.map(p => `<${p.closed ? 'polygon' : 'polyline'} stroke="${p.passId}" points="${p.points.map(q => `${q.x.toFixed(4)},${q.y.toFixed(4)}`).join(' ')}"/>`).join('')}</g></svg>`);
